#!/bin/bash
clear
echo -e "\033[1;32mDESEA DESISNTALAR  SSHPLUS MANAGER\033[1;33m"
read -p "Desea Eliminarr? [s/n] " -e -i s resp
[[ $resp = @(s|S|y|Y) ]] || exit 1
    rm -rf /bin/criarusuario expcleaner sshlimiter addhost bloqueo.sh hora.sh sshmonitor ajuda menu OpenVPN userbackup tcpspeed badvpn otimizar speedtest trafego banner senharoot reiniciarservicos reiniciarsistema attscript criarteste socks DropBear alterarlimite alterarsenha remover detalhes mudardata botssh infousers droplimiter conexao versao > /dev/null 2>&1
    rm -rf /etc/SSHPlus > /dev/null 2>&1
    clear
    echo -e "\033[1;36mgracias por utilizar  SSHPLUS MANAGER\033[1;33m"
    sleep 2
    cat /dev/null > ~/.bash_history && history -c && exit 0
return 0
